### ISSUE TITLE
Thank you for the good resource and three small questions. 

### ISSUE THREAD

**Issue by lookatthebrightside** [beliveau-lab/PaintSHOP_resources#2]
Hi there, 

Thank you again for providing such easy to use tools for coding dummies like me. 

I have three questions regarding using the platform: 
1. When I used the RNA probe design function to generate a list of probes for a gene on the positive strand, the platform outputted a series of probes, which I assume would match the (-) strand. However, the probe strand was shown in (+). Does that mean I still need to probeRC the outputs? 
2. When I retrieve the full-length cDNA sequence of a target gene and intersect the cDNA sequence with the probe sequences, am I expected to see 100% overlap for all the probes? I tried to randomly select probe sequences and intersect them with the cDNA sequences, but received poor match. What is the reason behind it? 
3. What would be the suggested numbers of probes I should use for highly-expressed and lowly-expressed genes? 

Thanks!

**Comment by elliothershberg** [comment]
Hi! I'm glad that you're enjoying PaintSHOP 😃 

These are good questions.

1. We make an effort to return probes of the correct strand. We do this by checking the strand of the RefSeq annotation, and taking the RC if necessary. (if you are curious, the function is here: https://github.com/beliveau-lab/PaintSHOP_pipeline/blob/master/workflow/scripts/probeDB.py#L106) It sounds like in our database, the RefSeq annotation was (-), which was why a (+) strand probe would be returned. If you are sure of the orientation you want, you could take the probeRC, or use the "DNA Probe Design" with the coordinates of your gene, where you can specify what strand you want. **edit:** I actually am checking if the current version of the pipeline accurately updates the `probe_strand` column. The sequence orientation is definitely correct, but that column may need to be updated. If so, we will handle this soon.
2. I'm not totally sure why you are seeing this. One reason could be that the cDNA would have exon-exon junctions which the probes would not intersect with. If you send an example, I'd be happy to take a look.
3. Irrespective of expression level, a good rule of thumb for RNA FISH is 15+ probes per target.

I hope that helps!

**Comment by lookatthebrightside** [comment]
Dear Elliot,

Thank you so much for your timely response! :D

To respond to your comments:
(1) I did read the documentation and understand that the platform will take
RC if necessary for users. However, when I typed in the following random
genes (2 on positive strand and 1 on negative strand), the outputs always
say probe strands were (+). Could it be because the way I was retrieving
the gene information is different from yours?
NM_080853.3 chr7 + --> probe strand (+)
NM_001312900.1 chr2 + --> probe strand (+)
NM_009215.1 chr16 -  --> probe strand (+)
(2) You could be right. The probe design was on the genomes not on the
post-splicing cDNAs. I should just order some probes to give those probes a
try (fastest way to know if they work)! :D



Many thanks!

**Comment by conorcamplisson** [comment]
Thanks for bringing this to our attention. Regarding probe strand, it looks like the probes are reverse complemented as needed, i.e. usable RNA binding probe sequences are generated in the case of both +/- annotations, however when probes are reverse complemented, the `probe_strand` value is not updated to reflect this strand inversion, which is why you are always seeing a + value in this field.

I have opened an issue in the pipeline repo [here](https://github.com/beliveau-lab/PaintSHOP_pipeline/issues/4) and will provide further updates there as we fix this bug. Thanks again!

**Comment by lookatthebrightside** [comment]
Thanks, Conor!
