### ISSUE TITLE
Include Rat files?

### ISSUE THREAD

**Issue by dpshepherd** [beliveau-lab/PaintSHOP_resources#3]
Thanks for the great resource! We just built the DNA & RNA databases for Rat using _rnor6.0_ and the default settings for  Paintshop_pipeline (T=42 C). If helpful, happy to host them for you to download and include in the S3 bucket.

If you'd prefer specific settings to be set during the probe mining, happy to re-run on our end as well.

**Comment by brianbeliveau** [comment]
Oh, that's fantastic to hear! Let me connect with you directly via email, there are a few moving parts here that might be better suited for that medium.

**Comment by dpshepherd** [comment]
Great! Best email is douglas.shepherd (at) asu.edu
