### ISSUE TITLE
add rhesus macaque genome?

### ISSUE THREAD

**Issue by nsmackler** [beliveau-lab/PaintSHOP_resources#4]
Hi Brian et al,

I tried to get PaintSHOP up and running on my cluster here at ASU, but I am clearly the worst postdoc in my lab and couldn't do it.

I also thought it might be useful to have this for the rest of the community since rhesus is a model organism. Although this is less altruistic than Doug Shepherd's issue where his lab ran PaintSHOP for rat and then asked if you wanted to use it...

Here is the most recent genome (Mmul_10)
https://uswest.ensembl.org/Macaca_mulatta/Info/Index

If you can't - then I'll try and find some more time to work it out and/or walk over to Doug's lab and see if he'll be even more altruistic... 

Thanks!

**Comment by brianbeliveau** [comment]
Hi Noah,

Would UCSC refGene annotations and Mmul_10 from here work for your purposes? Eg, http://hgdownload.soe.ucsc.edu/downloads.html#rhesus http://hgdownload.soe.ucsc.edu/goldenPath/rheMac10/bigZips/genes/

If so, this should be straightforward for us to process and add. If you specifically need Ensebml IDs, this would be a bigger ask on our end and would require some code development.

**Comment by nsmackler** [comment]
Thanks for the quick response! 

The UCSC refGene annotations and genome will be perfect. We can convert the Ensembl IDs to a format that will work with the PaintSHOP output.

Thanks again!

**Comment by brianbeliveau** [comment]
OK, great, we will get this into production in the near future. I'll leave this open for now as a reminder 😃

**Comment by conorcamplisson** [comment]
Added to PaintSHOP ( beliveau-lab/PaintSHOP@39bc83cc2ce9ac15b8011cff98c67e8d57803ea3 ) and re-deployed shiny app.
 
Thanks for the suggestion, @nsmackler !
