### ISSUE TITLE
What are the values in the columns?

### ISSUE THREAD

**Issue by kchen23** [beliveau-lab/PaintSHOP_resources#8]
chr1	10300	10329	CCCCAACCCCAACCCCAACCCCAACCCTAA	46.900	91.101	6552.797	1	0.871	51	+
chr1	10492	10521	CCGCCCGGGTCTGACCTGAGGAGAACTGTG	46.270	98.039	771.439	1	0.238	8	+
chr1	10522	10553	CTCCGCCTTCAGAGTACCACCGAAATCTGTGC	43.400	100.000	537.774	1	0.302	5	+

May I ask what are the columns? Thank you in advance!

**Comment by brianbeliveau** [comment]
Hi, they are specified here:

https://github.com/beliveau-lab/PaintSHOP_pipeline/blob/master/docs/pipeline_output.md
