### ISSUE TITLE
Column Names for hg38 newBalance DNA probes File

### ISSUE THREAD

**Issue by feizhao515** [beliveau-lab/PaintSHOP_resources#9]
Could you help me with the column names of the hg38 newBalance DNA probes file? There is no header for the file. Thank you very much!

**Comment by conorcamplisson** [comment]
Hello,

These columns are documented in the user guide [here](https://paintshop.io/user_guide/#DNA_Probe_Design). Let me know if you need any more info!

Best,

Conor

**Comment by feizhao515** [comment]
Thank you very much!

**Comment by feizhao515** [comment]
Hello Conor, Thank you so much for your reply. I wanted to ask  if the start and stop positions in the hg38 newBalance DNA probes file are 0-based or 1-based? Does actual region end one base before the stop coordinate? Thank you again for your help!
